#!/usr/bin/env bash

domain=$(sed -E -e 's_.*://([^/@]*@)?([^/:]+).*_\2_' <<< "$1")

wget \
     --recursive \
     --no-clobber \
     --page-requisites \
     --html-extension \
     --convert-links \
     --restrict-file-names=windows \
     --domains ${domain} \
     --no-parent \
         ${1}
